[project]
name = "agents-ai-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.9",
    "langgraph>=1.0.8",
    "praw>=7.7.1",
    "python-dotenv>=1.0.1",
]
